set(_CATKIN_CURRENT_PACKAGE "cpp_hw01")
set(cpp_hw01_VERSION "0.0.0")
set(cpp_hw01_MAINTAINER "lyq <lyq@todo.todo>")
set(cpp_hw01_PACKAGE_FORMAT "2")
set(cpp_hw01_BUILD_DEPENDS "fsd_common_msgs" "roscpp" "std_msgs" "opencv4" "cv_bridge" "sensor_msgs" "eigen" "visualization_msgs")
set(cpp_hw01_BUILD_EXPORT_DEPENDS "fsd_common_msgs" "roscpp" "std_msgs" "opencv4" "cv_bridge" "sensor_msgs" "eigen" "visualization_msgs")
set(cpp_hw01_BUILDTOOL_DEPENDS "catkin")
set(cpp_hw01_BUILDTOOL_EXPORT_DEPENDS )
set(cpp_hw01_EXEC_DEPENDS "fsd_common_msgs" "roscpp" "std_msgs" "opencv4" "cv_bridge" "sensor_msgs" "eigen" "visualization_msgs")
set(cpp_hw01_RUN_DEPENDS "fsd_common_msgs" "roscpp" "std_msgs" "opencv4" "cv_bridge" "sensor_msgs" "eigen" "visualization_msgs")
set(cpp_hw01_TEST_DEPENDS )
set(cpp_hw01_DOC_DEPENDS )
set(cpp_hw01_URL_WEBSITE "")
set(cpp_hw01_URL_BUGTRACKER "")
set(cpp_hw01_URL_REPOSITORY "")
set(cpp_hw01_DEPRECATED "")